@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'CDS View for Material'
@Metadata.ignorePropagatedAnnotations: true
define root view entity ZCDS_MATERIAL as select from ztab_material

{
    key product ,
    product_type ,
    crossplant_status ,
    crossplant_status_validity_dat ,
    creation_date ,
    created_by_user ,
    last_change_date  ,
    last_changed_by_user ,
    weight_unit as WeightUnit,
    purchase_order_quantity_unit ,
    source_of_supply ,
    country_of_origin,
    competitor_id ,
    product_group ,
    base_unit ,
    item_category_group ,
    product_hierarchy ,
    division ,
    varbl_pur_ord_unit_is_active ,
    anp_code ,
    brand ,
    procurement_rule ,
    validity_start_date ,
    low_level_code ,
    prodno_in_gen_prod_in_prepack_ ,
    serial_identifier_assgmt_profi ,
    size_or_dimension_text  ,
    industry_standard_name  ,
    product_standard_id,
    international_article_number_c ,
    product_is_configurable ,
    is_batch_management_required ,
    external_product_group ,
    crossplant_configurable_produc ,
    serial_no_explicitness_level ,
    product_manufacturer_number,
    manufacturer_number ,
    manufacturer_part_profile ,
    qlty_mgmt_in_procmt_is_active ,
    industry_sector ,
    change_number ,
    material_revision_level ,
    handling_indicator ,
    warehouse_product_group ,
    warehouse_storage_condition ,
    standard_handling_unit_type ,
    serial_number_profile ,
    adjustment_profile ,
    preferred_unit_of_measure ,
    is_pilferable ,
    is_relevant_for_hzds_substance ,
    quarantine_period ,
    time_unit_for_quarantine_perio ,
    quality_inspection_group ,
    authorization_group ,
    document_is_created_by_cad ,
    handling_unit_type ,
    has_variable_tare_weight ,
    last_change_datetime ,
    is_marked_for_deletion ,
    product_old_id 
}
