@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Data Definition for MDM Material Extension'
@Metadata.ignorePropagatedAnnotations: true
define root view entity ZDD_MDM_MAT_EXT as select from ztab_mdm_mat_ext

{




  // PURCHASING
  key material,
  key plant,
  material_text,
  plant_text,
  base_uom,
  base_uom_text,
  order_unit,
  order_unit_text,
  variable_po_unit,
  variable_po_unit_text,
  purchasing_group,
  purchasing_group_text,
  material_group,
  material_group_text,
  valid_from,
  plant_material_status,
  tax_indicator_material,
  tax_indicator_material_text,
  qual_freegoods_indicator,
  qual_freegoods_indicator_text,
  material_freight_group,
  material_freight_group_text,
  automatic_po,
  batch_management,
  batch_management_plant,
  purchasing_value_key,
  purchasing_value_key_text,
  reminder1_exped,
  reminder2_exped,
  reminder3_exped,
  std_value_delivery_var,
  shipping_instructions,
  underdelivery_tol,
  overdelivery_tol,
  min_delivery_qty,
  unlimited_overdelivery,
  acknowledgment_required,
  gr_processing_time,
  post_to_inspection_stock,
  jit_delivery,
  jit_delivery_text,
  critical_part,
  manufacturer_part_profile,
  manufacturer_part_profile_text,
  manufacturer,
  manufacturer_text,
  source_list_req,

  // PLANT DATA STORAGE 1
  location,
  location_text,
  storage_bin,
  storage_bin_text,
  picking_area,
  picking_area_text,
  storage_section,
  storage_condition,
  storage_condition_text,
  temperature_condition,
  temperature_condition_text,
  container_requirement,
  container_requirement_text,
  hazardous_material_number,
  hazardous_material_number_text,
  cc_phys_inv_ind,
  cc_phys_inv_ind_text,
  cc_fixed,
  number_gr_slips,
  label_type,
  label_type_text,
  label_form,
  label_form_text,
  appr_batch_record_req,
  max_storage_period,
  time_unit,
  minimum_remaining_shelf_life,
  total_shelf_life,
  period_ind_for_sled,
  period_ind_for_sled_text,
  storage_percentage,
  rounding_rule_sled,
  rounding_rule_sled_text,
  expiration_date,
  expiration_date_text,
  maturation_time,
  req_max_shelf_life,
  segmentation_strategy,
  segmentation_strategy_text,
  sort_stock,
  default_stock_segment,
  default_stock_segment_text,
  unit_of_issue,
  unit_of_issue_text,

  // PLANT DATA STORAGE 2
  @Semantics.quantity.unitOfMeasure: 'unit_of_issue'
  net_weight,

  @Semantics.quantity.unitOfMeasure: 'unit_of_issue'
  gross_weight,

  unit_of_weight,
  unit_of_weight_text,

  @Semantics.quantity.unitOfMeasure: 'unit_of_issue'
  volume,

  volume_unit,
  volume_unit_text,
  size_dimensions,
  neg_stocks_in_plant,
  serial_no_profile,
  profit_center,
  profit_center_text,
  iuid_relevant,
  iuid_type,
  iuid_type_text,
  log_handling_group,
  log_handling_group_text,
  distribution_profile,
  distribution_profile_text,
  stock_determination_group,
  stock_determination_group_text,
  external_allocation_uii,

  // SALES 1 AND 2
  division,
  division_text,
  x_distr_chain_status,
  x_distr_chain_status_text,
  gen_item_cat_group,
  gen_item_cat_group_text,
service_level
}

/*
//PURCHASING
    key material as Material,
    key plant as Plant,
    material_text as MaterialText,
    plant_text as PlantText,
    base_uom as BaseUom,
    base_uom_text as BaseUomText,
    order_unit as OrderUnit,
    order_unit_text as OrderUnitText,
    variable_po_unit as VariablePoUnit,
    variable_po_unit_text as VariablePoUnitText,
    purchasing_group as PurchasingGroup,
    purchasing_group_text as PurchasingGroupText,
    material_group as MaterialGroup,
    material_group_text as MaterialGroupText,
    valid_from as ValidFrom,
    plant_material_status as PlantMaterialStatus,
    tax_indicator_material as TaxIndicatorMaterial,
    tax_indicator_material_text as TaxIndicatorMaterialText,
    qual_freegoods_indicator as QualFreegoodsIndicator,
    qual_freegoods_indicator_text as QualFreegoodsIndicatorText,
    material_freight_group as MaterialFreightGroup,
    material_freight_group_text as MaterialFreightGroupText,
    automatic_po as AutomaticPo,
    batch_management as BatchManagement,
    batch_management_plant as BatchManagementPlant,
    purchasing_value_key as PurchasingValueKey,
    purchasing_value_key_text as PurchasingValueKeyText,
    reminder1_exped as Reminder1Exped,
    reminder2_exped as Reminder2Exped,
    reminder3_exped as Reminder3Exped,
    std_value_delivery_var as StdValueDeliveryVar,
    shipping_instructions as ShippingInstructions,
    underdelivery_tol as UnderdeliveryTol,
    overdelivery_tol as OverdeliveryTol,
    min_delivery_qty as MinDeliveryQty,
    unlimited_overdelivery as UnlimitedOverdelivery,
    acknowledgment_required as AcknowledgmentRequired,
    gr_processing_time as GrProcessingTime,
    post_to_inspection_stock as PostToInspectionStock,
    jit_delivery as JitDelivery,
    jit_delivery_text as JitDeliveryText,
    critical_part as CriticalPart,
    manufacturer_part_profile as ManufacturerPartProfile,
    manufacturer_part_profile_text as ManufacturerPartProfileText,
    manufacturer as Manufacturer,
    manufacturer_text as ManufacturerText,
    source_list_req as SourceListReq,
    
    
   // Plant Data Storage 1
 location, 
location_text, 
storage_bin, 
storage_bin_text, 
picking_area, 
picking_area_text, 
storage_section, 
storage_condition, 
storage_condition_text, 
temperature_condition, 
temperature_condition_text, 
container_requirement, 
container_requirement_text, 
hazardous_material_number, 
hazardous_material_number_text, 
cc_phys_inv_ind, 
cc_phys_inv_ind_text, 
cc_fixed, 
number_gr_slips, 
label_type, 
label_type_text, 
label_form, 
label_form_text, 
appr_batch_record_req, 
max_storage_period, 
time_unit, 
minimum_remaining_shelf_life, 
total_shelf_life, 
period_ind_for_sled, 
period_ind_for_sled_text, 
storage_percentage, 
rounding_rule_sled, 
rounding_rule_sled_text, 
expiration_date, 
expiration_date_text, 
maturation_time, 
req_max_shelf_life, 
segmentation_strategy, 
segmentation_strategy_text, 
sort_stock, 
default_stock_segment, 
default_stock_segment_text, 
unit_of_issue, 
unit_of_issue_text,


// Plant Data  Storage 2
 @Semantics.quantity.unitOfMeasure: 'unit_of_issue'
net_weight, 
 @Semantics.quantity.unitOfMeasure: 'unit_of_issue'
gross_weight, 
unit_of_weight, 
unit_of_weight_text, 
 @Semantics.quantity.unitOfMeasure: 'unit_of_issue'
volume, 
volume_unit, 
volume_unit_text, 
size_dimensions, 
neg_stocks_in_plant, 
serial_no_profile, 
profit_center, 
profit_center_text, 
iuid_relevant, 
iuid_type, 
iuid_type_text, 
log_handling_group, 
log_handling_group_text, 
distribution_profile, 
distribution_profile_text, 
stock_determination_group, 
stock_determination_group_text, 
external_allocation_uii,


//SALES 1 AND 2 
division                    ,
  division_text                ,
  x_distr_chain_status          ,
  x_distr_chain_status_text     ,
  gen_item_cat_group            ,
  gen_item_cat_group_text      

 */
  

